import type { Post, User } from '@/types'

export const mockUsers: Record<string, User> = {
  alice: { id: 'alice', name: 'Alice Smith', email: 'alice@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=alice', bio: 'Frontend engineer passionate about Vue and open-source.' },
  bob: { id: 'bob', name: 'Bob Johnson', email: 'bob@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=bob', bio: 'CSS enthusiast and UI designer.' },
  charlie: { id: 'charlie', name: 'Charlie Davis', email: 'charlie@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=charlie', bio: 'Full-stack developer focused on robust architectures.' },
  diana: { id: 'diana', name: 'Diana Evans', email: 'diana@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=diana', bio: 'UI/UX specialist creating accessible experiences.' },
}

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: 'Getting Started with Vue 3 and Composition API',
    excerpt: 'Learn the basics of the Composition API and how it compares to the Options API. We will cover setup, refs, reactive, and computed.',
    content: '<p>The Composition API is a set of additive, function-based APIs that allow flexible composition of component logic.</p><h2>Why Composition API?</h2><p>It solves the drawbacks of the Options API when dealing with large components. By grouping code logically rather than by options, your components become much easier to read and maintain as they scale.</p><p>We strongly recommend getting familiar with <code>ref</code> and <code>computed</code> first.</p>',
    author: mockUsers.alice,
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-01T10:00:00Z',
    category: 'Vue.js',
    tags: ['Frontend', 'JavaScript', 'Composition API'],
    views: 1250,
    likes: 120,
    bookmarks: 45,
    imageUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=1200&q=80',
    readingTime: 5
  },
  {
    id: '2',
    title: 'Mastering Tailwind CSS Grid and Flexbox',
    excerpt: 'A comprehensive guide to building complex layouts using Tailwind CSS utility classes without leaving your HTML.',
    content: '<p>Tailwind CSS provides a robust set of utility classes for layout management.</p><h2>Grid vs Flexbox</h2><p>While flexbox is excellent for 1-dimensional layouts, CSS Grid truly shines when you need 2-dimensional alignment. Tailwind makes both incredibly simple to use.</p>',
    author: mockUsers.bob,
    createdAt: '2023-10-05T14:30:00Z',
    updatedAt: '2023-10-06T09:15:00Z',
    category: 'CSS',
    tags: ['Design', 'Tailwind', 'Layout'],
    views: 890,
    likes: 89,
    bookmarks: 32,
    imageUrl: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=1200&q=80',
    readingTime: 8
  },
  {
    id: '3',
    title: 'Why TypeScript is Essential for Large Apps',
    excerpt: 'Discover the benefits of static typing, better tooling, and early error catching when scaling your JavaScript applications.',
    content: '<p>TypeScript has become the industry standard for large scale web applications.</p><h2>Catching Errors Early</h2><p>The compiler acts as your first line of defense, preventing entire classes of bugs before your code even runs in the browser.</p>',
    author: mockUsers.charlie,
    createdAt: '2023-10-10T08:45:00Z',
    updatedAt: '2023-10-10T08:45:00Z',
    category: 'TypeScript',
    tags: ['Architecture', 'JavaScript'],
    views: 3200,
    likes: 450,
    bookmarks: 112,
    imageUrl: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=1200&q=80',
    readingTime: 6
  },
  {
    id: '4',
    title: 'Building Reusable Components with shadcn-vue',
    excerpt: 'Step-by-step tutorial on integrating headless accessible components and styling them seamlessly with Tailwind.',
    content: '<p>Shadcn-vue provides beautifully designed, accessible components that you can copy and paste directly into your project.</p><h2>Why not an npm package?</h2><p>By owning the code, you get complete control over the styling and behavior without fighting against a strict library API.</p>',
    author: mockUsers.diana,
    createdAt: '2023-10-12T11:20:00Z',
    updatedAt: '2023-10-12T11:20:00Z',
    category: 'UI/UX',
    tags: ['Vue.js', 'Design', 'Components'],
    views: 1540,
    likes: 210,
    bookmarks: 85,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
    readingTime: 10
  },
  {
    id: '5',
    title: 'State Management with Pinia: The Modern Way',
    excerpt: 'Pinia is the new standard for Vue state management. See how to set up stores, use getters, and interact with the API.',
    content: '<p>Pinia is lightweight, type-safe, and modular.</p><h2>Stores the Vue 3 way</h2><p>With Pinia, you can create stores that feel exactly like composition API setup functions, making state management incredibly intuitive.</p>',
    author: mockUsers.alice,
    createdAt: '2023-10-15T16:00:00Z',
    updatedAt: '2023-10-15T16:00:00Z',
    category: 'Vue.js',
    tags: ['Frontend', 'State Management', 'Pinia'],
    views: 950,
    likes: 134,
    bookmarks: 56,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&q=80',
    readingTime: 4
  },
  {
    id: '6',
    title: 'Dark Mode Best Practices for Web Apps',
    excerpt: 'Implement a toggleable dark mode that respects system preferences and provides a comfortable reading experience.',
    content: '<p>Dark mode is no longer just a nice-to-have, it is an expected feature.</p><h2>Contrast and Readability</h2><p>Ensure that your dark colors have sufficient contrast ratios, and avoid pure black backgrounds which can cause eye strain.</p>',
    author: mockUsers.bob,
    createdAt: '2023-10-18T09:30:00Z',
    updatedAt: '2023-10-18T09:30:00Z',
    category: 'Design',
    tags: ['UI/UX', 'CSS', 'Accessibility'],
    views: 2100,
    likes: 310,
    bookmarks: 140,
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&q=80',
    readingTime: 7
  },
  {
    id: '7',
    title: 'Introduction to End-to-End Testing with Cypress',
    excerpt: 'Ensure your web applications work exactly as expected by writing robust E2E tests for your user flows.',
    content: '<p>Cypress brings reliable testing to the modern web.</p><h2>Writing your first test</h2><p>Cypress tests are written in JavaScript and interact with the browser exactly as a real user would, giving you immense confidence in your deployments.</p>',
    author: mockUsers.charlie,
    createdAt: '2023-10-22T13:15:00Z',
    updatedAt: '2023-10-22T13:15:00Z',
    category: 'Testing',
    tags: ['JavaScript', 'QA', 'E2E'],
    views: 780,
    likes: 65,
    bookmarks: 20,
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80',
    readingTime: 12
  }
]
